# Generated by Django 4.2 on 2026-06-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tutor_bank_account_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='users_stude_parent__ccecd2_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_phone',
        ),
    ]
