# Generated by Django 4.2 on 2026-06-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='feedback_re_class_i_610fe3_idx',
            old_name='feedback_re_class_id_index',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='feedback_re_user_id_0fa50d_idx',
            old_name='feedback_re_user_id_index',
        ),
    ]
