# Generated by Django 4.2 on 2026-06-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_enrollment_parent_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='finance_enr_status_110900_idx',
            old_name='finance_enr_status_class_index',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='finance_enr_student_e99c2f_idx',
            old_name='finance_enr_student_id_index',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_type_474675_idx',
            old_name='finance_tra_type_status_index',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_user_id_cdf42e_idx',
            old_name='finance_tra_user_id_index',
        ),
    ]
