# Generated by Django 4.2 on 2026-06-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_teaching_mode_hourly_rate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='class',
            new_name='classes_cla_status_940ffa_idx',
            old_name='classes_cla_status_index',
        ),
        migrations.RenameIndex(
            model_name='class',
            new_name='classes_cla_created_ec5000_idx',
            old_name='classes_cla_created_index',
        ),
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('staff_pending', 'Chờ nhân viên xử lý'), ('pending_admin', 'Chờ admin duyệt'), ('open', 'Công khai lớp'), ('waiting_parent', 'Chờ phụ huynh xác nhận'), ('waiting_tutor', 'Chờ gia sư xác nhận'), ('assigned', 'Đã phân công gia sư'), ('teaching', 'Đang học'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='open', max_length=20),
        ),
    ]
