# Generated by Django 4.2 on 2026-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_rename_classes_cla_status_index_classes_cla_status_940ffa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='total_sessions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
