# Generated by Django 4.2 on 2026-06-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_class_total_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
