# Generated by Django 4.2 on 2026-06-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_add_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('staff_pending', 'Chờ nhân viên xử lý'), ('pending_admin', 'Chờ admin duyệt'), ('open', 'Công khai lớp'), ('waiting_parent', 'Chờ phụ huynh xác nhận'), ('waiting_tutor', 'Chờ gia sư xác nhận'), ('waiting_student', 'Đang chờ học viên'), ('assigned', 'Đã phân công gia sư'), ('teaching', 'Đang học'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='open', max_length=20),
        ),
    ]
